### PR TITLE
add cta #26

### PR DESCRIPTION
**Pull request by NadhirahIzzati**
Screenshot (626)
Screenshot (627)
Screenshot (628)

### CODE REVIEW

**Review by rosclaritha — COMMENTED** [review]
remove the icon, make the shape fill background.

**Comment by NadhirahIzzati** [comment]
Screenshot (633)
Screenshot (632)
Screenshot (631)

**Comment by rosclaritha** [comment]
- [ ] remain previous color of the background
- [ ] the shape, kasi full tu background sampai hujung. contoh macam di bawah

image

**Comment by NadhirahIzzati** [comment]
Screenshot (640)
Screenshot (641)
Screenshot (642)

**Pull request merged**
